@extends('admin.layout') @section('title',($item?'Edit ':'Add ').$meta['singular']) @section('heading',($item?'Edit ':'Add ').$meta['singular']) @section('content')
@php $v=fn($key,$default='')=>old($key,$item[$key]??$default); $editing=(bool)$item; 
$resolveImg=fn($path)=>empty($path)?'':(\Illuminate\Support\Str::startsWith($path,['storage/','uploads/','images/'])?asset($path):asset('storage/'.$path));
@endphp
@if($errors->any())<div class="alert" style="background:#fff0f0;color:#9c2828">{{ $errors->first() }}</div>@endif
<form class="panel" style="margin-top:0" method="post" enctype="multipart/form-data" action="{{ $editing?route('admin.module.update',[$module,$item['id']]):route('admin.module.store',$module) }}">@csrf @if($editing) @method('PUT') @endif
<div class="section"><h3>Basic Information</h3><div class="form-grid"><div class="field"><label>Title / Name *</label><input name="title" required value="{{ $v('title') }}" placeholder="Enter {{ strtolower($meta['singular']) }} title"></div><div class="field"><label>URL Slug</label><input name="slug" value="{{ $v('slug') }}" placeholder="auto-generated-from-title"></div><div class="field"><label>Status</label><select name="status"><option value="draft" @selected($v('status')==='draft')>Draft</option><option value="published" @selected($v('status')==='published')>Published</option><option value="inactive" @selected($v('status')==='inactive')>Inactive</option></select></div><div class="field"><label>Featured Image</label>@if($editing && !empty($item['image']))<div style="margin-bottom:8px"><img src="{{ $resolveImg($item['image']) }}" style="height:60px;border-radius:4px;border:1px solid #ddd"></div>@endif<input type="file" name="image" accept="image/*"></div></div></div>

@if($module==='products')
<div class="section"><h3>Product Organization</h3><div class="form-grid"><div class="field full"><label>Categories (multiple allowed)</label><select name="categories[]" multiple size="6">@foreach($categories as $cat)<option value="{{ $cat['id'] }}" @selected(in_array($cat['id'],$v('categories',[])))>{{ $cat['title'] }}</option>@endforeach</select><small>First selected category becomes the primary category.</small></div><div class="field full"><label>Related Products</label><select name="related[]" multiple size="5">@foreach($products as $product)<option value="{{ $product['id'] }}" @selected(in_array($product['id'],$v('related',[])))>{{ $product['title'] }}</option>@endforeach</select></div></div></div>
<div class="section"><h3>Product Content & Media</h3><div class="form-grid"><div class="field full"><label>Short Description</label><textarea name="description">{{ $v('description') }}</textarea></div><div class="field full"><label>Long Description</label><textarea name="long_description" style="min-height:220px">{{ $v('long_description') }}</textarea></div><div class="field"><label>Image Alt Text</label><input name="alt_text" value="{{ $v('alt_text') }}"></div><div class="field"><label>Product Gallery</label>@if($editing && !empty($item['images'])) @php $imgs=is_string($item['images'])?json_decode($item['images'],true):$item['images']; @endphp @if(is_array($imgs)) <div style="display:flex;gap:8px;margin-bottom:8px;flex-wrap:wrap">@foreach($imgs as $img)<img src="{{ $resolveImg($img) }}" style="height:60px;border-radius:4px;border:1px solid #ddd">@endforeach</div> @endif @endif<input type="file" name="images[]" accept="image/*" multiple></div></div></div>
<div class="section"><h3>Product Specifications</h3><div class="form-grid">@foreach(['box_style'=>'Box Style','material'=>'Material / Stock','printing'=>'Printing Method','finishing'=>'Finishing','dimensions'=>'Dimensions','moq'=>'Minimum Order Quantity','turnaround'=>'Turnaround Time'] as $key=>$label)<div class="field"><label>{{ $label }}</label><input name="{{ $key }}" value="{{ $v($key) }}"></div>@endforeach</div></div>
<div class="section"><h3>Product FAQs</h3><div class="form-grid">@for($i=0;$i<4;$i++)<div class="field"><label>Question {{ $i+1 }}</label><input name="faq_question[]" value="{{ $v('faq_question.'.$i) }}"></div><div class="field"><label>Answer {{ $i+1 }}</label><textarea name="faq_answer[]" style="min-height:70px">{{ $v('faq_answer.'.$i) }}</textarea></div>@endfor</div></div>
@elseif($module==='categories')
<div class="section"><h3>Category Hierarchy</h3><div class="form-grid"><div class="field"><label>Parent Category</label><select name="parent_id"><option value="">— Top Level —</option>@foreach($categories as $cat) @if(!$item || (string)$cat['id']!==(string)$item['id'])<option value="{{ $cat['id'] }}" @selected((string)$v('parent_id')===(string)$cat['id'])>{{ $cat['title'] }}</option>@endif @endforeach</select></div><div class="field"><label>Navigation Icon</label>@if($editing && !empty($item['icon']))<div style="margin-bottom:8px"><img src="{{ $resolveImg($item['icon']) }}" style="height:60px;border-radius:4px;border:1px solid #ddd"></div>@endif<input type="file" name="icon" accept="image/*"></div></div></div>
<div class="section"><h3>Hero & Banner</h3><div class="form-grid"><div class="field"><label>Hero Title</label><input name="hero_title" value="{{ $v('hero_title') }}"></div><div class="field"><label>Hero Badge</label><input name="hero_badge" value="{{ $v('hero_badge') }}"></div><div class="field full"><label>Hero Description</label><textarea name="hero_description">{{ $v('hero_description') }}</textarea></div><div class="field"><label>Hero Image</label>@if($editing && !empty($item['hero_image']))<div style="margin-bottom:8px"><img src="{{ $resolveImg($item['hero_image']) }}" style="height:60px;border-radius:4px;border:1px solid #ddd"></div>@endif<input type="file" name="hero_image" accept="image/*"></div><div class="field"><label>Banner Image</label>@if($editing && !empty($item['banner_image']))<div style="margin-bottom:8px"><img src="{{ $resolveImg($item['banner_image']) }}" style="height:60px;border-radius:4px;border:1px solid #ddd"></div>@endif<input type="file" name="banner_image" accept="image/*"></div></div></div>
<div class="section"><h3>Category Sections</h3><div class="form-grid"><div class="field"><label>Products Heading</label><input name="products_heading" value="{{ $v('products_heading') }}"></div><div class="field"><label>Feature Title</label><input name="feature_title" value="{{ $v('feature_title') }}"></div><div class="field full"><label>Products Description</label><textarea name="products_description">{{ $v('products_description') }}</textarea></div><div class="field"><label>Why Choose Title</label><input name="why_choose_title" value="{{ $v('why_choose_title') }}"></div><div class="field"><label>Image Badge</label><input name="image_badge" value="{{ $v('image_badge') }}"></div><div class="field full"><label>Why Choose Description</label><textarea name="why_choose_description">{{ $v('why_choose_description') }}</textarea></div><div class="field full"><label>Category Description</label><textarea name="description" style="min-height:180px">{{ $v('description') }}</textarea></div></div></div>
<div class="section"><h3>Category FAQs</h3><div class="form-grid">@for($i=0;$i<4;$i++)<div class="field"><label>Question {{ $i+1 }}</label><input name="faq_question[]" value="{{ $v('faq_question.'.$i) }}"></div><div class="field"><label>Answer {{ $i+1 }}</label><textarea name="faq_answer[]" style="min-height:70px">{{ $v('faq_answer.'.$i) }}</textarea></div>@endfor</div></div>
@elseif($module==='blogs')
<div class="section"><h3>Article Details</h3><div class="form-grid"><div class="field"><label>Author Name</label><input name="author_name" value="{{ $v('author_name') }}"></div><div class="field"><label>Publish Date</label><input type="text" name="publish_date" value="{{ $v('publish_date') }}" placeholder="YYYY-MM-DD"></div><div class="field"><label>Category</label><input name="blog_category" value="{{ $v('blog_category') }}" placeholder="Design & Branding"></div><div class="field"><label>Tags / Tag Cloud</label><input name="tags" value="{{ $v('tags') }}" placeholder="rigid boxes, luxury, packaging"></div><div class="field full"><label>Excerpt</label><textarea name="excerpt">{{ $v('excerpt') }}</textarea></div><div class="field full"><label>Article Content</label><textarea name="content" style="min-height:300px">{{ $v('content') }}</textarea></div><div class="field full"><label>Author Description</label><textarea name="author_description">{{ $v('author_description') }}</textarea></div><div class="field"><label>Image Alt Text</label><input name="alt_text" value="{{ $v('alt_text') }}"></div></div></div>
@else
<div class="section"><h3>Page Content</h3><div class="form-grid"><div class="field"><label>Page Heading</label><input name="heading" value="{{ $v('heading') }}"></div><div class="field"><label>Menu Position</label><input type="number" name="position" value="{{ $v('position',0) }}"></div><div class="field"><label>Appearance / Template</label><select name="appearance"><option>Default</option><option>Policy</option><option>Landing Page</option><option>Contact</option></select></div><div class="field"><label>Image Alt Text</label><input name="alt_text" value="{{ $v('alt_text') }}"></div><div class="field full"><label>Page Content</label><textarea name="content" style="min-height:340px">{{ $v('content') }}</textarea></div></div></div>
@endif

<div class="section"><h3>SEO & Search Visibility</h3><div class="form-grid"><div class="field"><label>Meta Title</label><input name="meta_title" value="{{ $v('meta_title') }}"></div><div class="field"><label>Robots</label><select name="robots"><option value="index,follow">index, follow</option><option value="noindex,nofollow">noindex, nofollow</option></select></div><div class="field full"><label>Meta Description</label><textarea name="meta_description">{{ $v('meta_description') }}</textarea></div><div class="field full"><label>Meta Keywords / Tags</label><input name="meta_keywords" value="{{ $v('meta_keywords') }}"></div><div class="field full"><label>Schema JSON-LD</label><textarea name="schema" placeholder='{"@context":"https://schema.org"}'>{{ $v('schema') }}</textarea></div></div></div>
<div class="section"><h3>Visibility</h3><div class="checks"><label class="check"><input type="checkbox" name="show_home" value="1" @if((bool)$v('show_home')) checked @endif> Show on home page</label>@if($module==='categories')<label class="check"><input type="checkbox" name="show_in_nav" value="1" @if((bool)$v('show_in_nav')) checked @endif> Show in navigation</label>@endif @if($module==='blogs')<label class="check"><input type="checkbox" name="set_home" value="1" @if((bool)$v('set_home')) checked @endif> Feature on home</label>@endif</div></div>
<div class="actions"><a class="btn light" href="{{ route('admin.module.index',$module) }}">Cancel</a><button class="btn" type="submit">Save {{ $meta['singular'] }}</button></div></form>
@endsection
