<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up()
    {
        Schema::create('admin_categories', function (Blueprint $table) {
            $table->id(); $table->string('title'); $table->string('slug')->unique(); $table->foreignId('parent_id')->nullable()->constrained('admin_categories')->nullOnDelete();
            $table->string('status')->default('draft'); $table->boolean('show_in_nav')->default(false); $table->boolean('show_home')->default(false); $table->string('image')->nullable(); $table->string('icon')->nullable(); $table->string('hero_image')->nullable(); $table->string('banner_image')->nullable(); $table->text('hero_title')->nullable(); $table->text('hero_badge')->nullable(); $table->text('hero_description')->nullable(); $table->text('description')->nullable(); $table->text('products_heading')->nullable(); $table->text('products_description')->nullable(); $table->text('feature_title')->nullable(); $table->text('why_choose_title')->nullable(); $table->text('why_choose_description')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->text('meta_keywords')->nullable(); $table->string('robots')->default('index,follow'); $table->text('schema')->nullable(); $table->timestamps();
        });
        Schema::create('admin_products', function (Blueprint $table) {
            $table->id(); $table->string('title'); $table->string('slug')->unique(); $table->string('status')->default('draft'); $table->boolean('show_home')->default(false); $table->string('image')->nullable(); $table->text('images')->nullable(); $table->text('description')->nullable(); $table->longText('long_description')->nullable(); $table->string('alt_text')->nullable(); $table->string('box_style')->nullable(); $table->string('material')->nullable(); $table->string('printing')->nullable(); $table->string('finishing')->nullable(); $table->string('dimensions')->nullable(); $table->string('moq')->nullable(); $table->string('turnaround')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->text('meta_keywords')->nullable(); $table->string('robots')->default('index,follow'); $table->text('schema')->nullable(); $table->text('related')->nullable(); $table->timestamps();
        });
        Schema::create('admin_category_product', function (Blueprint $table) { $table->foreignId('product_id')->constrained('admin_products')->cascadeOnDelete(); $table->foreignId('category_id')->constrained('admin_categories')->cascadeOnDelete(); $table->primary(['product_id','category_id']); });
        Schema::create('admin_product_faqs', function (Blueprint $table) { $table->id(); $table->foreignId('product_id')->constrained('admin_products')->cascadeOnDelete(); $table->text('question'); $table->longText('answer'); $table->timestamps(); });
        Schema::create('admin_category_faqs', function (Blueprint $table) { $table->id(); $table->foreignId('category_id')->constrained('admin_categories')->cascadeOnDelete(); $table->text('question'); $table->longText('answer'); $table->timestamps(); });
        Schema::create('admin_blogs', function (Blueprint $table) { $table->id(); $table->string('title'); $table->string('slug')->unique(); $table->string('status')->default('draft'); $table->boolean('show_home')->default(false); $table->string('image')->nullable(); $table->string('author_name')->nullable(); $table->date('publish_date')->nullable(); $table->string('blog_category')->nullable(); $table->text('tags')->nullable(); $table->text('excerpt')->nullable(); $table->longText('content')->nullable(); $table->text('author_description')->nullable(); $table->string('alt_text')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->text('meta_keywords')->nullable(); $table->string('robots')->default('index,follow'); $table->text('schema')->nullable(); $table->timestamps(); });
        Schema::create('admin_pages', function (Blueprint $table) { $table->id(); $table->string('title'); $table->string('slug')->unique(); $table->string('status')->default('draft'); $table->boolean('show_home')->default(false); $table->string('image')->nullable(); $table->string('heading')->nullable(); $table->longText('content')->nullable(); $table->unsignedInteger('position')->default(0); $table->string('appearance')->default('Default'); $table->string('alt_text')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->text('meta_keywords')->nullable(); $table->string('robots')->default('index,follow'); $table->text('schema')->nullable(); $table->timestamps(); });
    }
    public function down() { foreach (['admin_product_faqs','admin_category_faqs','admin_category_product','admin_products','admin_categories','admin_blogs','admin_pages'] as $table) Schema::dropIfExists($table); }
};
